openapi: 3.0.3
info:
  contact:
    email: team@nlpsandbox.io
    name: NLP Sandbox Team
    url: https://nlpsandbox.io
  description: |
    # Introduction
    This NLP tool takes as input a clinical note and returned a de-identified version of the note.
    This design of this API is a work in progress.
    # Examples
    - [NLP Sandbox PHI Deidentifier](https://github.com/nlpsandbox/phi-deidentifier)
  license:
    name: Apache 2.0
    url: https://github.com/nlpsandbox/nlpsandbox-schemas/blob/develop/LICENSE
  title: NLP Sandbox PHI Deidentifier API
  version: 1.1.2
  x-logo:
    url: https://nlpsandbox.github.io/nlpsandbox-schemas/logo.png
servers:
- url: http://example.com/api/v1
- url: https://example.com/api/v1
tags:
- description: Operations about deidentified notes
  name: DeidentifiedNote
- description: Operations about health checks
  name: HealthCheck
- description: Operations about this tool
  name: Tool
paths:
  /deidentifiedNotes:
    post:
      description: Returns the deidentified note
      operationId: create_deidentified_notes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeidentifyRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeidentifyResponse'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Invalid request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request cannot be fulfilled due to an unexpected server
            error
      summary: Deidentify a clinical note
      tags:
      - DeidentifiedNote
      x-openapi-router-controller: openapi_server.controllers.deidentified_note_controller
  /healthCheck:
    get:
      description: Get information about the health of the service
      operationId: get_health_check
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
          description: Success
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The specified resource was not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request cannot be fulfilled due to an unexpected server
            error
      summary: Get health check information
      tags:
      - HealthCheck
      x-openapi-router-controller: openapi_server.controllers.health_check_controller
  /tool:
    get:
      description: Get information about the tool
      operationId: get_tool
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tool'
          description: Success
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The specified resource was not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request cannot be fulfilled due to an unexpected server
            error
      summary: Get tool information
      tags:
      - Tool
      x-openapi-router-controller: openapi_server.controllers.tool_controller
  /tool/dependencies:
    get:
      description: Get the dependencies of this tool
      operationId: get_tool_dependencies
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToolDependencies'
          description: Success
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The specified resource was not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request cannot be fulfilled due to an unexpected server
            error
      summary: Get tool dependencies
      tags:
      - Tool
      x-openapi-router-controller: openapi_server.controllers.tool_controller
components:
  responses:
    BadRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Invalid request
    InternalServerError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The request cannot be fulfilled due to an unexpected server error
    NotFound:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The specified resource was not found
  schemas:
    NoteId:
      description: The ID of the clinical note
      example: awesome-note
      maxLength: 60
      minLength: 3
      pattern: ^[a-z0-9]+(?:-[a-z0-9]+)*$
      type: string
    PatientId:
      description: The ID of the FHIR patient
      example: awesome-patient
      maxLength: 60
      minLength: 3
      pattern: ^[a-z0-9]+(?:-[a-z0-9]+)*$
      type: string
    Note:
      description: A clinical note
      example:
        identifier: awesome-note
        text: On 12/26/2020, Ms. Chloe Price met with Dr. Prescott in Seattle.
        type: loinc:LP29684-5
        patientId: awesome-patient
      properties:
        identifier:
          description: The ID of the clinical note
          example: awesome-note
          maxLength: 60
          minLength: 3
          pattern: ^[a-z0-9]+(?:-[a-z0-9]+)*$
          type: string
        text:
          description: The content of the clinical note
          type: string
        type:
          description: The note type (LOINC concept)
          type: string
        patientId:
          description: The ID of the FHIR patient
          example: awesome-patient
          maxLength: 60
          minLength: 3
          pattern: ^[a-z0-9]+(?:-[a-z0-9]+)*$
          type: string
      required:
      - identifier
      - patientId
      - text
      - type
      type: object
    MaskingCharConfig:
      description: Configuration for the masking char strategy. E.g. "John Smith lives
        at 123 Main St" -> "********* lives at ***********".
      properties:
        maskingChar:
          default: '*'
          description: Character used to mask sensitive information
          maxLength: 1
          minLength: 1
          type: string
      type: object
    AnnotationTypeMaskConfig:
      description: Configuration for the "annotation type" strategy. E.g. "John Smith
        lives at 123 Main St" -> "[PERSON_NAME] lives at [PHYSICAL_ADDRESS]".
      type: object
    RedactConfig:
      description: Configuration for the redaction strategy. E.g. "John Smith lives
        at 123 Main St" -> "lives at".
      type: object
    DateOffsetConfig:
      description: Configuration for the "date offset" strategy. E.g. "John Smith
        visited on 1 January 2020" -> "John Smith visited on 29 October 2025". Note,
        can only be set with the "text_date" annotation type.
      properties:
        offsetDays:
          description: Number of days by which to offset annotated dates.
          type: integer
      required:
      - offsetDays
      type: object
    DeidentificationStep:
      description: The configuration of a deidentification step
      properties:
        confidenceThreshold:
          default: 0
          description: The minimum confidence level for a given annotation to be de-identified
          example: 95.5
          format: float
          maximum: 100
          minimum: 0
          type: number
        maskingCharConfig:
          $ref: '#/components/schemas/MaskingCharConfig'
        annotationTypeMaskConfig:
          description: Configuration for the "annotation type" strategy. E.g. "John
            Smith lives at 123 Main St" -> "[PERSON_NAME] lives at [PHYSICAL_ADDRESS]".
          type: object
        redactConfig:
          description: Configuration for the redaction strategy. E.g. "John Smith
            lives at 123 Main St" -> "lives at".
          type: object
        dateOffsetConfig:
          $ref: '#/components/schemas/DateOffsetConfig'
        annotationTypes:
          description: The types of annotations to which the de-identifer should apply
            the selected strategy
          items:
            enum:
            - text_date
            - text_person_name
            - text_physical_address
            - text_id
            - text_contact
            type: string
          type: array
      required:
      - annotationTypes
      type: object
    DeidentifyRequest:
      description: A request to de-identify a clinical note
      example:
        deidentificationSteps:
        - confidenceThreshold: 20
          maskingCharConfig:
            maskingChar: '-'
          annotationTypes:
          - text_date
        - confidenceThreshold: 30
          maskingCharConfig:
            maskingChar: '#'
          annotationTypes:
          - text_person_name
        - confidenceThreshold: 20
          annotationTypeMaskConfig: {}
          annotationTypes:
          - text_physical_address
        note:
          identifier: awesome-note
          text: On 12/26/2020, Ms. Chloe Price met with Dr. Prescott in Seattle.
          type: loinc:LP29684-5
          patientId: awesome-patient
      properties:
        note:
          $ref: '#/components/schemas/Note'
        deidentificationSteps:
          description: A list of deidentification steps
          items:
            $ref: '#/components/schemas/DeidentificationStep'
          type: array
      required:
      - deidentificationSteps
      - note
      type: object
    TextAnnotation:
      description: An annotation in a text
      example:
        start: 42
        length: 19
        text: the annotation text
        confidence: 95.5
      properties:
        start:
          description: The position of the first character
          type: integer
        length:
          description: The length of the annotation
          type: integer
        text:
          description: The string annotated
          type: string
        confidence:
          description: The confidence in the accuracy of the annotation
          format: float
          maximum: 100
          minimum: 0
          type: number
      required:
      - confidence
      - length
      - start
      - text
      type: object
    TextDateAnnotation:
      allOf:
      - $ref: '#/components/schemas/TextAnnotation'
      - $ref: '#/components/schemas/TextDateAnnotation_allOf'
      description: A date annotation in a text
      example:
        start: 42
        length: 10
        text: 10/26/2020
        dateFormat: MM/DD/YYYY
        confidence: 95.5
      type: object
    TextPersonNameAnnotation:
      allOf:
      - $ref: '#/components/schemas/TextAnnotation'
      description: A person name annotation in a text
      example:
        start: 42
        length: 11
        text: Chloe Price
        confidence: 95.5
      type: object
    TextPhysicalAddressAnnotation:
      allOf:
      - $ref: '#/components/schemas/TextAnnotation'
      - $ref: '#/components/schemas/TextPhysicalAddressAnnotation_allOf'
      description: A physical address annotation in a text
      example:
        start: 42
        length: 7
        text: Seattle
        addressType: city
        confidence: 95.5
      type: object
    TextIdAnnotation:
      allOf:
      - $ref: '#/components/schemas/TextAnnotation'
      - $ref: '#/components/schemas/TextIdAnnotation_allOf'
      description: An ID annotation in a text
      example:
        start: 42
        length: 11
        text: 203-11-4535
        idType: ssn
        confidence: 95.5
      type: object
    TextContactAnnotation:
      allOf:
      - $ref: '#/components/schemas/TextAnnotation'
      - $ref: '#/components/schemas/TextContactAnnotation_allOf'
      description: A contact annotation in a text
      example:
        start: 42
        length: 11
        text: dave@uw.edu
        contactType: email
        confidence: 95.5
      type: object
    AnnotationSet:
      description: Set of annotations of all types for a text
      example:
        textDateAnnotations:
        - start: 42
          length: 10
          text: 10/26/2020
          dateFormat: MM/DD/YYYY
          confidence: 95.5
        - start: 42
          length: 10
          text: 10/26/2020
          dateFormat: MM/DD/YYYY
          confidence: 95.5
        textPersonNameAnnotations:
        - start: 42
          length: 11
          text: Chloe Price
          confidence: 95.5
        - start: 42
          length: 11
          text: Chloe Price
          confidence: 95.5
        textPhysicalAddressAnnotations:
        - start: 42
          length: 7
          text: Seattle
          addressType: city
          confidence: 95.5
        - start: 42
          length: 7
          text: Seattle
          addressType: city
          confidence: 95.5
        textIdAnnotations:
        - start: 42
          length: 11
          text: 203-11-4535
          idType: ssn
          confidence: 95.5
        - start: 42
          length: 11
          text: 203-11-4535
          idType: ssn
          confidence: 95.5
        textContactAnnotations:
        - start: 42
          length: 11
          text: dave@uw.edu
          contactType: email
          confidence: 95.5
        - start: 42
          length: 11
          text: dave@uw.edu
          contactType: email
          confidence: 95.5
      properties:
        textDateAnnotations:
          description: Date annotations in a text
          items:
            $ref: '#/components/schemas/TextDateAnnotation'
          type: array
        textPersonNameAnnotations:
          description: Person name annotations in a text
          items:
            $ref: '#/components/schemas/TextPersonNameAnnotation'
          type: array
        textPhysicalAddressAnnotations:
          description: Physical address annotations in a text
          items:
            $ref: '#/components/schemas/TextPhysicalAddressAnnotation'
          type: array
        textIdAnnotations:
          description: ID annotations in a text
          items:
            $ref: '#/components/schemas/TextIdAnnotation'
          type: array
        textContactAnnotations:
          description: Contact annotations in a text
          items:
            $ref: '#/components/schemas/TextContactAnnotation'
          type: array
      required:
      - textContactAnnotations
      - textDateAnnotations
      - textIdAnnotations
      - textPersonNameAnnotations
      - textPhysicalAddressAnnotations
      type: object
    DeidentifyResponse:
      description: The response to a deidentification request
      example:
        deidentifiedAnnotations:
          textDateAnnotations:
          - start: 42
            length: 10
            text: 10/26/2020
            dateFormat: MM/DD/YYYY
            confidence: 95.5
          - start: 42
            length: 10
            text: 10/26/2020
            dateFormat: MM/DD/YYYY
            confidence: 95.5
          textPersonNameAnnotations:
          - start: 42
            length: 11
            text: Chloe Price
            confidence: 95.5
          - start: 42
            length: 11
            text: Chloe Price
            confidence: 95.5
          textPhysicalAddressAnnotations:
          - start: 42
            length: 7
            text: Seattle
            addressType: city
            confidence: 95.5
          - start: 42
            length: 7
            text: Seattle
            addressType: city
            confidence: 95.5
          textIdAnnotations:
          - start: 42
            length: 11
            text: 203-11-4535
            idType: ssn
            confidence: 95.5
          - start: 42
            length: 11
            text: 203-11-4535
            idType: ssn
            confidence: 95.5
          textContactAnnotations:
          - start: 42
            length: 11
            text: dave@uw.edu
            contactType: email
            confidence: 95.5
          - start: 42
            length: 11
            text: dave@uw.edu
            contactType: email
            confidence: 95.5
        deidentifiedNote:
          identifier: awesome-note
          text: On 12/26/2020, Ms. Chloe Price met with Dr. Prescott in Seattle.
          type: loinc:LP29684-5
          patientId: awesome-patient
        originalAnnotations:
          textDateAnnotations:
          - start: 42
            length: 10
            text: 10/26/2020
            dateFormat: MM/DD/YYYY
            confidence: 95.5
          - start: 42
            length: 10
            text: 10/26/2020
            dateFormat: MM/DD/YYYY
            confidence: 95.5
          textPersonNameAnnotations:
          - start: 42
            length: 11
            text: Chloe Price
            confidence: 95.5
          - start: 42
            length: 11
            text: Chloe Price
            confidence: 95.5
          textPhysicalAddressAnnotations:
          - start: 42
            length: 7
            text: Seattle
            addressType: city
            confidence: 95.5
          - start: 42
            length: 7
            text: Seattle
            addressType: city
            confidence: 95.5
          textIdAnnotations:
          - start: 42
            length: 11
            text: 203-11-4535
            idType: ssn
            confidence: 95.5
          - start: 42
            length: 11
            text: 203-11-4535
            idType: ssn
            confidence: 95.5
          textContactAnnotations:
          - start: 42
            length: 11
            text: dave@uw.edu
            contactType: email
            confidence: 95.5
          - start: 42
            length: 11
            text: dave@uw.edu
            contactType: email
            confidence: 95.5
      properties:
        originalAnnotations:
          $ref: '#/components/schemas/AnnotationSet'
        deidentifiedAnnotations:
          $ref: '#/components/schemas/AnnotationSet'
        deidentifiedNote:
          $ref: '#/components/schemas/Note'
      type: object
    Error:
      description: Problem details (tools.ietf.org/html/rfc7807)
      properties:
        title:
          description: A human readable documentation for the problem type
          type: string
        status:
          description: The HTTP status code
          type: integer
        detail:
          description: A human readable explanation specific to this occurrence of
            the problem
          type: string
        type:
          description: An absolute URI that identifies the problem type
          type: string
      required:
      - status
      - title
      type: object
    HealthCheck:
      description: Represents the health of a service
      example:
        status: pass
      properties:
        status:
          description: Indicates whether the service status is acceptable or not
          enum:
          - pass
          - fail
          - warn
          type: string
      required:
      - status
      type: object
    License:
      description: The license (license keyword used by GitHub)
      enum:
      - afl-3.0
      - apache-2.0
      - artistic-2.0
      - bsl-1.0
      - bsd-2-clause
      - bsd-3-clause
      - bsd-3-clause-clear
      - cc
      - cc0-1.0
      - cc-by-4.0
      - cc-by-sa-4.0
      - wtfpl
      - ecl-2.0
      - epl-1.0
      - epl-2.0
      - eupl-1.1
      - agpl-3.0
      - gpl
      - gpl-2.0
      - gpl-3.0
      - lgpl
      - lgpl-2.1
      - lgpl-3.0
      - isc
      - lppl-1.3c
      - ms-pl
      - mit
      - mpl-2.0
      - osl-3.0
      - postgresql
      - ofl-1.1
      - ncsa
      - unlicense
      - zlib
      - none
      example: apache-2.0
      type: string
    ToolType:
      description: The type of this tool
      example: nlpsandbox:date-annotator
      maxLength: 60
      minLength: 3
      pattern: ^[a-z0-9]+(?:-[a-z0-9]+)*(:)[a-z0-9]+(?:-[a-z0-9]+)*$
      type: string
    Tool:
      description: Information about an NLP tool
      example:
        name: awesome-nlp-tool
        version: 1.0.6
        license: apache-2.0
        repository: github:awesome-org/awesome-nlp-tool
        description: An awesome NLP Tool that takes as input X and outputs Y.
        author: Awesome Team
        authorEmail: author@example.com
        url: https://example.com
        type: nlpsandbox:date-annotator
        apiVersion: 1.1.2
      properties:
        name:
          description: The tool name
          maxLength: 60
          minLength: 3
          pattern: ^[a-z0-9]+(?:-[a-z0-9]+)*$
          type: string
        version:
          description: The version of the tool (SemVer string)
          minLength: 1
          pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
          type: string
        license:
          $ref: '#/components/schemas/License'
        repository:
          description: The place where the code lives
          type: string
        description:
          description: A short, one-sentence summary of the tool
          maxLength: 100
          type: string
        author:
          description: The author of the tool
          type: string
        authorEmail:
          description: The email address of the author
          format: email
          type: string
        url:
          description: The URL to the homepage of the tool
          format: uri
          type: string
        type:
          description: The type of this tool
          example: nlpsandbox:date-annotator
          maxLength: 60
          minLength: 3
          pattern: ^[a-z0-9]+(?:-[a-z0-9]+)*(:)[a-z0-9]+(?:-[a-z0-9]+)*$
          type: string
        apiVersion:
          description: The version of the tool OpenAPI specification
          minLength: 1
          pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
          type: string
      required:
      - apiVersion
      - author
      - authorEmail
      - description
      - license
      - name
      - repository
      - type
      - url
      - version
      type: object
    ToolDependencies:
      description: A list of tool dependencies
      example:
        tools:
        - name: awesome-nlp-tool
          version: 1.0.6
          license: apache-2.0
          repository: github:awesome-org/awesome-nlp-tool
          description: An awesome NLP Tool that takes as input X and outputs Y.
          author: Awesome Team
          authorEmail: author@example.com
          url: https://example.com
          type: nlpsandbox:date-annotator
          apiVersion: 1.1.2
        - name: awesome-nlp-tool
          version: 1.0.6
          license: apache-2.0
          repository: github:awesome-org/awesome-nlp-tool
          description: An awesome NLP Tool that takes as input X and outputs Y.
          author: Awesome Team
          authorEmail: author@example.com
          url: https://example.com
          type: nlpsandbox:date-annotator
          apiVersion: 1.1.2
      properties:
        tools:
          description: A list of tools
          items:
            $ref: '#/components/schemas/Tool'
          type: array
      required:
      - tools
      type: object
    TextDateAnnotation_allOf:
      properties:
        dateFormat:
          description: Date format (ISO 8601)
          example: MM/DD/YYYY
          type: string
      type: object
    TextPhysicalAddressAnnotation_allOf:
      properties:
        addressType:
          description: Type of address information
          enum:
          - city
          - country
          - department
          - hospital
          - organization
          - other
          - room
          - state
          - street
          - zip
          type: string
      required:
      - addressType
      type: object
    TextIdAnnotation_allOf:
      properties:
        idType:
          description: Type of ID information
          enum:
          - account
          - bio_id
          - device
          - health_plan
          - id_number
          - license
          - medical_record
          - ssn
          - vehicle
          - other
          type: string
      required:
      - idType
      type: object
    TextContactAnnotation_allOf:
      properties:
        contactType:
          description: Type of contact information
          enum:
          - email
          - fax
          - ip_address
          - phone
          - url
          - other
          type: string
      required:
      - contactType
      type: object
